### ISSUE TITLE
Erreur de duplication d'enregistrement dans les tables

### ISSUE THREAD

**Issue by eptakam** [dorian-404/easy-feed#6]
Lors de la création des modèles, nous avons voulu avoir certaines attributs de types charfields comme clé primaire. Cela créait comme des doublons dans les données lors des enregistrements sur les tables ayant des relations plusieurs à plusieurs. Le nombre de duplicats correspondant au nombre d'enregistrements dans la table parent. 
Pour résoudre cela, nous avons tout simplement laisser la charge à Django de créer les clés primaires et avons rendu ces attributs que nous souhaitions avoir comme clés primaires, uniques.
![Screenshot 2024-04-29 083753](https://github.com/dorian-404/easy-feed/assets/134623891/201fdf40-fda2-4903-9d07-af58c47690cd)

**Comment by dorian-404** [comment]
Parfait merci d'avoir documenter l'issue
