### ISSUE TITLE
Plusieurs vues qui pontent sur la même template

### ISSUE THREAD

**Issue by eptakam** [dorian-404/easy-feed#7]
Au départ, c'était un casse-tête: comment faire lorsque j'ai plus d'une qui retournent du contenu vers une seule et même template, surtout sachant que chaque vue à son url?
Ce que nous avons fait c'est juste de le faire dans une seule vue et à la fin renvoyer un dictionnaire (clé: valeur) dont chacune des clés est en fait ce que devait retourner chacune des vues comme sur la capture ci-jointe:
![Screenshot 2024-05-22 113408](https://github.com/dorian-404/easy-feed/assets/134623891/a7a2a386-a7ef-44ce-94e0-c530db0f80c4)

**Comment by dorian-404** [comment]
Parfait merci pour ta réponse a l'issue
